### ISSUE TITLE
Abstract vs concrete?

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/AbstractGPs.jl#104]
Hi, I came across the [POMDPs.jl Software paper](https://www.jmlr.org/papers/v18/16-300.html) and it reminded me of a point I had thought of before - what should "AbstractGP.jl" be? From the name, I had imagined it as a way of defining the "interface" of what GPs should look like in Julia - similar to what POMDPs.jl does, with concrete implementations in other packages (see https://github.com/JuliaPOMDP/). However, despite the name, there are lots of concrete implementations in here. What's the motivation for having them in here (rather than, for example, providing a "base GP" package implementing the AbstractGP interface)? Splitting it up that way might help encourage both more exploration by the community (trying out new ways of implementing the same interface) as well as increasing cohesion/interoperability by those. Right now, even though it's called "AbstractGP", it doesn't seem clear to someone coming from the outside that they really ought to fit their GP work in this interface. What are your thoughts on this?

**Comment by willtebbutt** [comment]
That's a fair point.

The intention was certainly that all of the stuff in [here](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/src/abstract_gp/abstract_gp.jl) would be pure interface stuff.

My feeling was that you probably do want to bundle _some_ standard functionality in with the interface. Perhaps we would benefit from decomposing stuff further? Or maybe we just need better documentation?

I agree that there is a surprisingly long list of things in this package for something that claims to be an interface package when compared to `ChainRulesCore`, for example.

**Comment by willtebbutt** [comment]
Actually yeah, looking through our documentation, we've really not properly highlighted the fact that we've defined an interface.

**Comment by willtebbutt** [comment]
I believe that this was resolved a while ago
