### ISSUE TITLE
Logistic for inducing points locations

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#107]
In the docs, the VI example the inducing points locations are passed through the logistic function. Although I suppose it's for keeping them between 0 and 1, it's not explained anywhere and I don't think it's necessary either?

**Comment by devmotion** [comment]
It's mentioned in the text:
> that the pseudo-points are in the unit interval [0,1] with the logistic function ...

I assume the idea is that all the data are from this interval and all plots are restricted to this interval, so by constraining the inducing points one gains some consistency. I am not sure though if this argument is completely convincing.

**Comment by theogf** [comment]
Oh I see! I read too fast :flushed: . A small improvement would be to use a slightly different notation for the softplus and logistic function. Right now both are called f(x).
