### ISSUE TITLE
Specialised Plotting Inputs for FiniteGP

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#113]
Our plotting functionality currently assumes that when plotting a `FiniteGP` `f(x)`, we wish to visualise it at the inputs `x`. While this assumption generally holds, there's currently no escape hatch (beyond circumventing the plotting functionality entirely!) if this doesn't hold.

My particular use case is that I have a `FiniteGP` `f(x)` whose dimensions I wish to plot on the x-axis at some other set of points `z`.

I'm not super familiar with plotting recipes, @theogf or @devmotion , do you know how I might we might extend our existing functionality to make this work?

**Comment by devmotion** [comment]
I could try to extend the plotting recipes but unfortunately it is not completely clear to me what additional functionality you would like to have.

Currently, we just plot the marginals of a `FiniteGP`, which is a projection of a GP at some fixed points `x`, versus the points `x`. Can you explain maybe with an example what you would like to plot instead?

**Comment by willtebbutt** [comment]
Great. So, concrete example:
```julia
z = randn(10)
x = randn(10)
f = GP(SEKernel())
plot(z, f(x))
```
should produce something similar to
```julia
plot(z, mean(f(x)); ribbon=std(f(x)))
```
(modulo our usual formatting defaults)

**Comment by devmotion** [comment]
Great, I think I know how the recipe has to be extended to account for this case. I'll prepare a PR.

**Comment by theogf** [comment]
Could you explain what's your use case? I don't understand why you need this.

**Comment by willtebbutt** [comment]
The situation I've got is analogous to wanting to plot a single output from a multi-output GP. The inputs `x` for such a GP will be a vector of `Tuple`s (or some abstraction based around that does actually instantiate said vector fully), the first element of which is the index of the output, the second the location in space on which your multi-output GP lives.

So the current plotting functionality won't know how to plot `f(x)`, because it doesn't know how to handle `x`, but with this addition I'll be able to say `plot(last.(x), f(x))` and get the thing that I need.

(I'm not actually doing this with multi-output GPs, I'm refactoring Stheno to use AbstractGPs properly and trying to get AbstractGPs' plotting functionality to play nicely with that)
