### ISSUE TITLE
GP only takes AbstractVector as an argument

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#12]
Is there any reason why one cannot pass a matrix to a `GP` object ?
```julia
f = GP(SqExponentialKernel())
fx = f(randn(3, 100)) # fails
```

**Comment by willtebbutt** [comment]
Yup, by convention requires either a `ColVecs` or `RowVecs` otherwise how do you know what convention the user is employing?

**Comment by theogf** [comment]
Shouldn't we do like in KF.jl and put a wrapper for matrices by adding a `obsdim` keyword? Or decide of an arbitrary order?

**Comment by willtebbutt** [comment]
I really don't see what the advantage is over just using `ColVecs` / `RowVecs`. One way of doing things is strictly better than two unless there's a really good reason to have two ways of doing things.

**Comment by theogf** [comment]
This is probably going to be the same dialog again but :
I really don't believe we should force users to "convert" their data in a different format. I agree that it should be used in the internals but the user should not have to see it.
Again as a lambda user if I want to use a package I would just like to throw my matrix to the model eventually giving what is the dimensionality without having to wrap it first into some format.

**Comment by willtebbutt** [comment]
Agreed, this is going to go down the same line again.

> Again as a lambda user if I want to use a package I would just like to throw my matrix to the model eventually giving what is the dimensionality without having to wrap it first into some format.

At the risk of labouring the point, wrapping your matrix _is_ telling the package how to treat the dimensions of your data, nothing more. I really can't see what the difference is from the user's perspective between writing
```julia
f(ColVecs(X))
```
and
```julia
f(X; obsdim=2)
```
, particularly if we provide a good error message for `f(X)` that says how to handle multi-input data.

In any case, I'll concede this point if you're really keen on it being a thing, and given that it's consistent with KF

**Comment by theogf** [comment]
> I really can't see what the difference is from the user's perspective

In one case, `obsdim` is pretty obviously the observation dimension, on the other side with `ColVecs` I will need to go through the docs, understand what it is and what it does and how to correctly use it.

> In any case, I'll concede this point if you're really keen on it being a thing, and given that it's consistent with KF

Thanks! I will take care of making the PR

On the other hand, I have to say the structure is already pretty nice to use and I am looking forward to integrate it to AGP.jl
