### ISSUE TITLE
Rename `cov_diag` to `var`?

### ISSUE THREAD

**Issue by devmotion** [JuliaGaussianProcesses/AbstractGPs.jl#124]
Distributions.jl uses `var` for the diagonal of the covariance matrix and, e.g., defines a fallback for `AbstractMvNormal`: https://github.com/JuliaStats/Distributions.jl/blob/35125579a77b938f8d4a8bd2be23cbf1f2ddf225/src/multivariate/mvnormal.jl#L258

So to avoid that users end up with surprisingly inefficient code we could
- define `Statistics.var(gp::FiniteGP) = cov_diag(gp)`
- or rename `cov_diag` to `var`

What would you prefer?

**Comment by theogf** [comment]
Renaming `cov_diag` to `Statistics.var` sounds great to me!

**Comment by willtebbutt** [comment]
If we were to do this, I'd want to rename all of the places where we refer to diagonals, such as `mean_and_cov_diag` -> `mean_and_var` to ensure that we're consistent.

**Comment by devmotion** [comment]
Yes, I agree, I thought about this as well and wanted to suggest it but somehow forgot to mention it above :smile:
