### ISSUE TITLE
Better error messages for AbstractGP

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#137]
Rereading #89 it makes me think that the error messages for stuff like `mean(f::AbstractGP)` are awful (`cannot iterate over crazy type, etc`).
I would be in favor in returning an error message giving maybe a quick explanation and referring to read the docs!

**Comment by willtebbutt** [comment]
Yeah -- I get hit by this a lot. Would be very happy to review a PR that addresses this.

**Comment by theogf** [comment]
Will do tomorrow!
