### ISSUE TITLE
Some usability suggestions

### ISSUE THREAD

**Issue by kaandocal** [JuliaGaussianProcesses/AbstractGPs.jl#154]
Taken from [this issue](https://github.com/theogf/AugmentedGaussianProcesses.jl/issues/88#issuecomment-849919054_) in AugmentedGaussianProcesses.jl:

> There seems to be no simple way of accessing observations in a PosteriorGP except via data.x and data.δ

As there is a standard API for creating a PosteriorGP it would make sense to also provide one for retrieving its contents. How about `getX` and `gety`?

> `rand(gp, x)` as an alternative to `rand(gp(x))` similar to mean, cov etc.
> `convert(Normal, gp, x)` or `convert(MvNormal, gp, X)` would be convenient

As `FiniteGP isa AbstractMvNormal` the last point is probably not relevant.

**Comment by kaandocal** [comment]
As an addition I should note that while AbstractGP defines itself as a more low-level interface I was wondering if there wouldn't be some value in providing some more "high-level" functionality for updating a GP with new training points (like a push! functionality) and changing kernel parameters (for hyperparameter tuning). Both of these tasks can be achieved at the moment but it's a bit ugly.

**Comment by devmotion** [comment]
I guess a reason for why there is no API for destructuring a `PosteriorGP` is that [it is not part of the public API](https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev/api/#Internal-AbstractGPs-API):

> This functionality is not intended to be used directly by the users, or those building functionality on top of this package – they should interact with Primary Public API.

I am also unsure about `rand`, to me it seems `rand(gp, x)` would be neither consistent with [Random](https://docs.julialang.org/en/v1/stdlib/Random/) nor with Distributions. But I guess the same can be said about `mean(gp, x)`, even though also this function [is not part of the public API](https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev/api/#Statistics.mean-Tuple{AbstractGPs.AbstractGP,%20AbstractVector{T}%20where%20T}).

**Comment by kaandocal** [comment]
I see! Looks like somebody should have read the documentation more carefully. In any case it doesn't look like the public API is yet sufficient for implementing something like Bayesian Optimisation... I guess functions like `mean(gp, x)` are useful to avoid computing variances if only the mean is required, which doesn't apply to `rand`. I am still a bit unsure about parts of AbstractGPs so please bear with me!

**Comment by willtebbutt** [comment]
Thanks for opening an issue to discuss this -- very keen to have feedback.

> some more "high-level" functionality for updating a GP with new training points

On this particular point, I would note that you can call `posterior` on a `PosteriorGP`, and it does indeed just update with the new data points and provide a new `PosteriorGP`.

> and changing kernel parameters (for hyperparameter tuning)

This is intentionally something that hasn't been built into AbstractGPs.jl. My personal view is that things like ParameterHandling.jl in conjunction with Zygote.jl and Optim.jl make life sufficiently straightforward so as not to bother with much more of a high-level API. For example, [this example in TemporalGPs.jl](https://github.com/JuliaGaussianProcesses/TemporalGPs.jl#learning-kernel-parameters-with-optimjl-parameterhandlingjl-and-zygotejl) shows how the packages play nicely together.

That being said, I can see the appeal of having a scikit-learn like interface built on top of these tools that's quite opinionated 🤷  I don't personally feel that AbstractGPs is the right place for something like that though.

> In any case it doesn't look like the public API is yet sufficient for implementing something like Bayesian Optimisation

Could you elaborate a bit more on this? I'd be keen to know what you feel is lacking.

**Comment by kaandocal** [comment]
The issue with another interface is that we might end up with three layers of abstraction with very little underneath. For now AbstractGP's purpose seems quite clear and we should probably focus on doing that well.

> This is intentionally something that hasn't been built into AbstractGPs.jl. My personal view is that things like ParameterHandling.jl in conjunction with Zygote.jl and Optim.jl make life sufficiently straightforward so as not to bother to make a high-level API less important. For example, this example in TemporalGPs.jl shows how the packages play nicely together.

I fully second this. Some kind of consistent interface like that in Flux (with `Flux.params`, `Flux.trainable`) would be a nice goal to strive towards but as long as it's easy and clearly documented we'll be fine. I agree that the above example is maybe a bit too manual but it's serviceable and any improvements would probably belong to ParameterHandling.jl. Something like @functor for parameters maybe?

**Comment by kaandocal** [comment]
> Could you elaborate a bit more on this? I'd be keen to know what you feel is lacking.

So far the main thing I have come across is accessing training data for a GP. I will try to put up a tentative Bayesian Optimisation demo soon so we can see how well things work together.

**Comment by willtebbutt** [comment]
> I fully second this. Some kind of consistent interface like that in Flux (with Flux.params, Flux.trainable) would be a nice goal to strive towards but as long as it's easy and clearly documented we'll be fine. I agree that the above example is maybe a bit too manual but it's serviceable and any improvements would probably belong to ParameterHandling.jl. Something like @functor for parameters maybe?

Glad you agree! Regarding `@functor` etc, my view is that it's just an orthogonal parameter handling strategy to the one adopted by `ParameterHandling.jl`. The former is very much a "build a model and mutate it" strategy, whereas ParameterHandling.jl natural lends itself to a more immutable approach to handling models and objective functions etc.

> The issue with another interface is that we might end up with three layers of abstraction with very little underneath. 

Yeah -- I definitely don't want to have it in this package. I was imagining writing a small glue package that implements MLJ's (or whichever your favourite scikit-learn-like package is) interface using this packages tooling. The whole package would probably only be a couple of hundred lines of code or something, and wouldn't provide the flexibility that is availlable here, but could make life easier in some situations.

> So far the main thing I have come across is accessing training data for a GP. I will try to put up a tentative Bayesian Optimisation demo soon so we can see how well things work together.

Interesting -- I very much look forward to seeing this! I like your proposal above about adding some helper functionality to access training data, and having a concrete example to work backwards from would be very helpful.

**Comment by willtebbutt** [comment]
Closing as this has gone stale. Please re-open if needed.
