### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#161]
We're currently going through a ChainRulesCore breaking change. AbstractGPs has to wait for both Turing.jl and Soss.jl to update as well before it's possible for us to update -- they're fantastic packages of course, but they're dependency-heavy so tend to take a little while to update everything.

I definitely want to ensure that we're testing against them, but I wonder whether it would make sense to have (at least) two separate CI runs -- one for the core functionality of AbstractGPs, and another to run Turing and Soss (or possibly separate runners for Turing and Soss?).

This would mean that we'd be able to plough ahead with upgrades for AbstractGPs provided that our "core" tests pass, but we would be kept apprised of whether or not AbstractGPs interacts properly with Soss and Turing.

Thoughts?

**Comment by devmotion** [comment]
I think this would make sense, we already separated them into a separate environment since Soss is only compatible with Julia >= 1.5.

**Comment by devmotion** [comment]
So it would be a trivial change, we basically just have introduce a new "GROUP" value (maybe "PPL"?) and add an action that runs it.
