### ISSUE TITLE
mean_and_cov_diag not defined for predictions with 

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#17]
With a given `m isa PosteriorGP`, `mean_and_diag_cov` does not work when calling it on `m(Xtest)`
MWE:
```julia
using AbstractGPs, KernelFunctions
x = rand(10)
y = rand(10)
k = SqExponentialKernel()
m = posterior(GP(k)(x, 0.01), y)
mean_and_cov_diag(m(x))
```

**Comment by willtebbutt** [comment]
Ah, yes, so this isn't actually defined for anything. It is intended that you one uses `marginals(f(x))`, which returns a `Vector` or `Normal` distributions.

`mean_and_cov_diag` is meant to be an internal method. That it is exported is a mistake.

**Comment by theogf** [comment]
I actually find it pretty useful! It makes it easier to plot the marginal distribution. (I know there are recipes but I prefer to do my own)

**Comment by willtebbutt** [comment]
I'm unclear why this is easier than `marginals`. For example,
```julia
fs = marginals(f(x))
mean.(fs)
std.(fs)
var.(fs)
quantile(fs, 0.99)
```
etc all work if you have the marginals, but
```julia
means, vars = mean_and_cov_diag(f(x))
```
just gives you the means and variances, so you have to manually implement computations such as
```julia
means .+ 3 .* sqrt.(vars)
means .+ 3 .* sqrt(vars)
```
rather than simply writing
```julia
quantile.(fs, 0.99)
quantile.(fs, 0.01)
```
(or whichever level you're interested in).

**Comment by theogf** [comment]
Well with `Plots.jl` I would just do 
`plot(x, means, ribbon= sqrt.(vars))`
But that's fair that you can just do `mean.(fs)` and `var.(fs)` and that's cleaner.

**Comment by willtebbutt** [comment]
Ooo I had no idea that `ribbon` is a thing. Good to know.

If you could review #18 that would be great.
