### ISSUE TITLE
plot() recipe returns unexpected prediction intervals

### ISSUE THREAD

**Issue by azev77** [JuliaGaussianProcesses/AbstractGPs.jl#173]
```julia
# Load dataset.
using HTTP, CSV, DataFrames, Dates
link = "https://bit.ly/3vtTaW5";
r = HTTP.get(link);
df = CSV.read(r.body, DataFrame; missingstring="NA");

using AbstractGPs, Plots
X = 0:1.0:(length(df.date)-1) 
Y = df.value;
XH = 0:1.0:(length(df.date)-1 +5) 

f = GP(Matern32Kernel()) # Define GP prior w Matern32 kernel
fx = f(X, 0.001)         # Finite projection at the inputs `X` 
logpdf(fx, Y)            # -512 # Data's log-likelihood w.r.t prior GP `f`. 
p_fx = posterior(fx, Y)  # Exact posterior given `Y`.
logpdf(p_fx(X), Y)       # 184 # Data's LL w.r.t prior posterior GP `p_fx`.

px = XH[end-4:end]
pm = mean.(marginals(p_fx(XH))[end-4:end])
ps = std.(marginals(p_fx(XH))[end-4:end])

# Plot posterior.
scatter(X, Y; label="Data")
plot!(XH, f(XH, 0.001); label="Prior")
plot!(p_fx(XH), label="Posterior" )
scatter!(px, pm, lab = "oos prediction μ")
scatter!(px, pm - 1.0*ps, lab="oos prediction μ - σ") 
scatter!(px, pm + 1.0*ps, lab="oos prediction μ + σ") 
```
![image](https://user-images.githubusercontent.com/7883904/122110865-0a60ee80-cded-11eb-9f93-9f2862422eb5.png)
It looks like the plot() recipe returns `μ ± 1.0σ` instead of (what I'd expect) `μ ± 1.96σ`.
Is this intended? Can this be customized?

**Comment by azev77** [comment]
Looks like it might be set to 1.0 here:
https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/0e223c8cd57d625c9476f9e4365beaf80b7fad14/src/util/plotting.jl#L6

Not sure & idk how to modify it...

**Comment by theogf** [comment]
The 1.96sigma  corresponds to the 95%quantile but there is no particular reason to prefer it to just 1sigma or 2 sigma.
What would you expect 1.96 in particular?

**Comment by azev77** [comment]
>  What would you expect 1.96 in particular?
Not sure what you mean. 

How can I make `plot(p_fx(XH) )` return a plot with `μ ± 1.96σ`?

**Comment by theogf** [comment]
If I am not mistaking you can pass the kwarg `scale=1.96`

**Comment by theogf** [comment]
No sorry it should be `ribbon_scale=1.96`

**Comment by azev77** [comment]
It works now:
```julia
    plot(p_fx(XH), lab="oos prediction μ - σ")
    plot!(p_fx(XH),ribbon_scale=1.96, lab="oos prediction μ - 1.96σ")
```
![image](https://user-images.githubusercontent.com/7883904/122116155-47c87a80-cdf3-11eb-871d-7eba897b148d.png)

**Comment by azev77** [comment]
While we're here. I asked the following question in [other repos](https://github.com/stanfordmlgroup/ngboost/issues/200): 
A [recent paper](https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr794.pdf?la=en) makes 1 year ahead predictions for the distribution of GDP growth, with [current GDP growth](https://fred.stlouisfed.org/series/A191RL1Q225SBEA) & [NFCI](https://www.chicagofed.org/publications/nfci/index) as conditioning variables. Their [data & Matlab code is here](https://www.openicpsr.org/openicpsr/project/113169/version/V1/view?flag=follow&pageSize=100&sortOrder=(?title)&sortAsc=true). 
Target variable `y_{t+1} = GDP_Growth_{t+1}`
predictors `X_t =(y_t, NFCI_t) = (GDP_Growth_{t}, NFCI_t)`
Goal: predict the conditional distribution `P(y_{t+1} | y_{t}, NFCI_t )`
 ![image](https://user-images.githubusercontent.com/7883904/122104934-33ca4c00-cde6-11eb-8f95-ef4ece092d30.png)
The authors use quantile regression.
Is it possible to produce this kind of figure w/ `AbstractGPs`? 
Are GPs good at this type of thing rel to [NGBoost](https://github.com/stanfordmlgroup/ngboost).py?
