### ISSUE TITLE
Arithmetic between GPs

### ISSUE THREAD

**Issue by jtrakk** [JuliaGaussianProcesses/AbstractGPs.jl#175]
I have two `AbstractGPs.FiniteGP` instances fit with Optim.  I want to know the difference between their predictions. One way to do this is to make predictions from each and take the difference.   I think it is also possible to take the difference between the two FiniteGPs to get a new FiniteGP, and use that to make a prediction of the difference at an input point? 

If so, does it make sense to add that feature to AbstractGPs.jl ?

**Comment by willtebbutt** [comment]
Have you seen Stheno.jl at all? It implements these kinds of operations between GPs.
