### ISSUE TITLE
Should AbstractGPs reexport KernelFunctions?

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#19]
I think it would make sense for `AbstractGPs` to reexport `KernelFunctions.jl` via [Reexport.jl](https://github.com/simonster/Reexport.jl). Or at least reexport all the `Kernel` (by iteratively going over the subtypes).
Connected to a demand in #17

**Comment by willtebbutt** [comment]
I would be pro- this -- it doesn't make sense to make the user to load both KernelFunctions and AbstractGPs. I've not used Reexport.jl so please feel free to open a PR.
