### ISSUE TITLE
Approximate Inference

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#193]
Currently, we have
```julia
approx_posterior(approximation, fx, y, u)
```
As pointed out by @st-- and @rossviljoen in [SparseGPs.jl](https://github.com/rossviljoen/SparseGPs.jl/issues/13), we should consider reducing this to a 3-arg function in which `approximation` contains `u`, since `u` is really a component of the approximation. This kind of thing would generalise more elegantly to what @rossviljoen is doing in `SparseGPs.jl`, as it will be natural in that case to put the variational parameters associated with `q(u)` inside `approximation` as well. More generally, there are approximate inference algorithms which don't involve pseudo-points, and it would be nice to generalise to them also.

So the new `approx_posterior` function for the saturated `VFE` approximation would be something like
```julia
approx_posterior(VFE(u), fx, y)
```
and for the unsaturated would be something like
```julia
approx_posterior(VFE(u, qu), fx, y)
```
(or something a bit like that).

**Comment by willtebbutt** [comment]
I wonder whether we actually just want to keep the same function names and always pass an `approximation` argument?

For example,
```julia
posterior(approximation, fx, y)
logpdf(approximation, fx, y)
rand(rng, approximation, fx)
```
etc?

**Comment by st--** [comment]
@rossviljoen @willtebbutt is this sufficiently resolved by #194 ?

**Comment by st--** [comment]
Reviving this discussion, another question is where should the computation/optimisation go? E.g. for SparseVariationalApproximation we need to optimise to find the optimal q(u), and currently this is left as an exercise for the user, and `posterior(sva, lfx, y)` is then super fast (and ignores the last two arguments entirely). In contrast, `posterior(LaplaceApproximation(), lfx, y)` actually computes the mode of the posterior. From a user perspective, it'd be nice if it was consistent (and easy...).

**Comment by willtebbutt** [comment]
Yeah -- I at least think we ought to be able to do this in the deterministic-objective case (no minibatching, quadrature / exact reconstruction-term computation) at the very least. I've done something like this in `ConjugateComputationVI.jl` (which I should move over to here and align with what you've done with the Laplace approximation).

**Comment by willtebbutt** [comment]
I believe that this is now stale, so am closing.
