### ISSUE TITLE
Unecessary computation for `FiniteGP`

### ISSUE THREAD

**Issue by cscherrer** [JuliaGaussianProcesses/AbstractGPs.jl#232]
Say you're using GPs in a PPL. The setup might be something like
```julia
julia> using AbstractGPs

julia> X = randn(20, 1);

julia> ydist = GP(Matern32Kernel())(RowVecs(X));
```

Then in Soss or Turing, you might have `y ~ ydist`.

Digging into the AbstractGPs code, it looks like both `rand` and `logpdf` end up doing
```julia
m, C_mat = mean_and_cov(ydist)  # `f` in the code
C = cholesky(_symmetric(C_mat))
```
Since none of this depends on the actual data, it could be computed once and reused many times during inference. As it is, this adds lots of overhead at each iteration. Is there a reason not to do it this way?

**Comment by devmotion** [comment]
It's not necessary to compute it if you don't call `rand` or `logpdf` :shrug: 

One approach that doesn't touch the structure of `FiniteGP` would be to add a method `MvNormal(::FiniteGP)` that returns the corresponding `MvNormal` distribution which could then be used instead of `FiniteGP` if you don't want to recompute the cholesky decomposition, e.g., if you call `rand` or `logpdf` multiple times.

**Comment by cscherrer** [comment]
> It's not necessary to compute it if you don't call `rand` or `logpdf` shrug
> 
> One approach that doesn't touch the structure of `FiniteGP` would be to add a method `MvNormal(::FiniteGP)` that returns the corresponding `MvNormal` distribution which could then be used instead of `FiniteGP` if you don't want to recompute the cholesky decomposition, e.g., if you call `rand` or `logpdf` multiple times.

Ooh, I like that. Maybe we have a `@require` in MeasureTheory that adds the `MvNormal` method. Then we can use the faster representation too, should work out great!

**Comment by devmotion** [comment]
E.g., it is not required if you compute the marginals. Or more generally just the mean and covariance matrix.

> Maybe we have a @require in MeasureTheory that adds the MvNormal method

I don't think this should be done, this would be type piracy (and use Requires...). It belongs into AbstractGPs if we think it is a good idea.

**Comment by willtebbutt** [comment]
> Just to be sure I understand, what else would you do with a FiniteGP? I can think of kernel composition, but doesn't that come before this? Maybe there are other operations?

There are a number of scenarios in which ways to compute `logpdf`, `rand`, `posterior` etc don't utilise the covariance matrix directly. For example, TemporalGPs.jl never computes any covariance matrices, but implements `logpdf`, `rand`, `posterior`, etc.

**Comment by cscherrer** [comment]
> Haha, my suggestion was `Distributions.MvNormal` since `FiniteGP` is already a subtype of `Distributions.AbstractMvNormal` smile

Right, I'd want to get to the fast implementation in MultivariateMeasures.jl, and avoid type piracy :)

But come to think of it, maybe it should just be `MeasureTheory.MvNormal(::Distributions.AbstractMvNormal)`. Then I wouldn't need `Requires`.

BTW, is there a way to avoid using PDMats? I'd rather allow positive semidefinite coavariance.

> There are a number of scenarios in which ways to compute `logpdf`, `rand`, `posterior` etc don't utilise the covariance matrix directly. For example, TemporalGPs.jl never computes any covariance matrices, but implements `logpdf`, `rand`, `posterior`, etc.

Interesting, does it need to avoid using `FiniteGP` to do that?

**Comment by devmotion** [comment]
> BTW, is there a way to avoid using PDMats? I'd rather allow positive semidefinite coavariance.

You can use `PSDMat` in https://github.com/invenia/PDMatsExtras.jl.

**Comment by willtebbutt** [comment]
I believe that this is basically sorted, so am going to close. Please re-open if you feel otherwise.
