### ISSUE TITLE
Incomplete implementation of <: AbstractMvNormal

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#242]
If we actually define `FiniteGP <: AbstractMvNormal` we should follow the API defined in https://github.com/JuliaStats/Distributions.jl/blob/master/src/multivariate/mvnormal.jl, i.e.

- [x] `length(d)` :        vector dimension
- [x] `mean(d)`:          the mean vector (in full form)
- [x] `cov(d)`:           the covariance matrix (in full form)
- [ ] `invcov(d)`:        inverse of covariance
- [ ] `logdetcov(d)`:     log-determinant of covariance
- [ ] `sqmahal(d, x)` :        Squared Mahalanobis distance to center
- [ ] `sqmahal!(r, d, x)`:    Squared Mahalanobis distances
- [ ] `gradlogpdf(d, x)`:     Gradient of logpdf w.r.t. x
- [x] `_rand!(d, x)`:         Sample random vector(s)
- [ ] `params(d)`

**Comment by willtebbutt** [comment]
Yeah, we should probably implement these things. Does Distributions provide any API testing suites that we can utilise?

**Comment by devmotion** [comment]
Of course, not :smile: I always wanted to have some though (for all kinds of distributions), so a PR would be great :stuck_out_tongue:

**Comment by willtebbutt** [comment]
Also, are there fallback definitions for any of these that we get for free?

**Comment by theogf** [comment]
Haha I was going to say the same. It seems it's already there in the tests though:
https://github.com/JuliaStats/Distributions.jl/blob/master/test/mvnormal.jl

**Comment by theogf** [comment]
> Also, are there fallback definitions for any of these that we get for free?

Only `sqmahal` can fallback on `sqmahal!`

**Comment by willtebbutt** [comment]
> Haha I was going to say the same. It seems it's already there in the tests though:

Nice. @devmotion would you be open to a PR that pretty much just moves that function into `src`? (Into a submodel called `TestUtils` or whatever)

**Comment by devmotion** [comment]
In principle, it would be possible to define fallbacks for `logdetcov` and `invcov` as well :thinking: I don't know why they are not included.

**Comment by theogf** [comment]
> > Haha I was going to say the same. It seems it's already there in the tests though:
> 
> Nice. @devmotion would you be open to a PR that pretty much just moves that function into `src`? (Into a submodule called `TestUtils` or whatever)

The tests are from 2014 :exploding_head: https://github.com/JuliaStats/Distributions.jl/commit/c2dbc8e586b55d670f1924dab6d990bfdfbe326f

**Comment by devmotion** [comment]
> Nice. @devmotion would you be open to a PR that pretty much just moves that function into `src`? (Into a submodule called `TestUtils` or whatever)

Yes, this would be great! Maybe one has to clean and polish the tests a bit though. In general, the test infrastructure is a mess (in particular the JSON files :see_no_evil:).

**Comment by theogf** [comment]
> The tests are from 2014 exploding_head [JuliaStats/Distributions.jl@c2dbc8e](https://github.com/JuliaStats/Distributions.jl/commit/c2dbc8e586b55d670f1924dab6d990bfdfbe326f)

Ah no sorry they've been modified since, just the API is from this time

**Comment by willtebbutt** [comment]
> (in particular the JSON files 🙈)

😬 

> Yes, this would be great!

Excellent. I've just found a new way to procrastinate.

**Comment by willtebbutt** [comment]
https://github.com/JuliaStats/Distributions.jl/pull/1418

**Comment by willtebbutt** [comment]
@theogf  you'll now find a test suite in `src/test_utils.jl` in Distributions.jl.

**Comment by willtebbutt** [comment]
@theogf I guess this can be closed now?
