### ISSUE TITLE
`GP`'s call should not accept matrix (without RowVecs/ColVecs)

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/AbstractGPs.jl#257]
It'd be better to raise an error (and explicitly point people to RowVecs/ColVecs) - it just took me fifteen minutes to figure out why the assert length(fx) == length(y) failed for me :facepalm:

**Comment by willtebbutt** [comment]
Ah, yes, this thing. @theogf is a fan of matrices, so we have support for it. I continue to favour throwing an informative error message.

**Comment by theogf** [comment]
Aren't matrices automatically converted to ColVecs?

**Comment by willtebbutt** [comment]
Good point. What was the context that you had the above issue in @st-- ?

**Comment by st--** [comment]
The context was a matrix but in the wrong shape (RowVecs-style)..

**Comment by theogf** [comment]
How about having a mandatory keyword for matrices then?

**Comment by devmotion** [comment]
Maybe we just need a better error message for matrices? Eg `length is not compatible` and if the other dimension would be compatible add something like `did you specify observations as rows (default is columns)? In this case please specify obsdim keyword argument or use RowVecs`?

IMO it would be good to be consistent with KernelFunctions which currently allows matrices and uses `obsdim = 2` as default. I'm fine with omitting a default value in both packages (if it doesn't break too much) but I think we should keep them consistent.

**Comment by devmotion** [comment]
If we keep the default of columns as observations maybe also it could be stated (more clearly) in the documentation.

**Comment by st--** [comment]
Yeah, better messages would be good. How about adding an `@info` message when passing in a matrix, which clarifies which way around it's being interpreted (and it'd be easy to turn off by simply wrapping in ColVecs/RowVecs as appropriate)?
