### ISSUE TITLE
[QUESTION] Using AbstractGPs.jl with Zygote

### ISSUE THREAD

**Issue by vikram-s-narayan** [JuliaGaussianProcesses/AbstractGPs.jl#285]
Is there a way to use Zygote with AbstractGPs.jl? 

To illustrate my question better, could you please let me know how I can rewrite the equivalent of the last two lines to output the gradient?

```
using AbstractGPs
using Zygote

abstract type MyAbstractSurrogate <: Function end 

mutable struct AbstractGPStruct{X, Y, L, U,GP, GP_P} <: MyAbstractSurrogate
    x::X
    y::Y
    lb::L
    ub::U
    gp::GP 
    gp_posterior::GP_P
 end

function AbstractGPSurrogate(x, y, lb, ub; gp = GP(Matern52Kernel()), Σy = 0.1)
    AbstractGPStruct(x, y, lb, ub, gp, posterior(gp(x, Σy),y))
 end

function (g::AbstractGPStruct)(val)
    return mean(g.gp_posterior(val))
end

lb = 0.0
ub = 3.0
sqr = x -> x^2 
x = [ 1.125, 2.625, 1.875, 0.375, 0.5625]
y = sqr.(x)
agp1D = AbstractGPSurrogate(x,y, lb, ub, gp=GP(SqExponentialKernel()), Σy=0.05)
x_new = 2.5
y_actual = sqr.([x_new]) #6.25
y_predicted = agp1D([x_new]) #6.15; 

gsqr1(x) = gradient(sqr, x) #for illustrative purposes; we want to do something similar with agp1D
gsqr1(2.5)


# the following code does not work; 
# how can one rewrite this to make it work with AbstractGPs.jl?
gsqr2(x) = gradient(agp1D, x) 
gsqr2([2.5]) #"LoadError: Output is an array, so the gradient is not defined. Perhaps you wanted jacobian."

```

**Comment by willtebbutt** [comment]
Hi @vikram-s-narayan 

Zygote's `gradient` function applies only to functions that output a real number e.g. a loss / objective function, but it looks to me like the `agp1D` function outputs a `struct`.

The standard objective function for a GP is the log marginal probability (I would strongly recommend reading some of the introductory material in [this textbook](http://www.gaussianprocess.org/gpml/) if you're unfamiliar). Looking at your struct, you probably want something like `logpdf(agp1D.gp(agp1D.x), agp1D.y)`, which computes the log marginal probability of observing `y` at `x` under the `gp`.

**Comment by theogf** [comment]
@willtebbutt I don't think that's the issue, `agp1D` is a struct viewed as functor.
Your problem is that `return mean(g.gp_posterior(val))` returns a vector
Change the functor to 
```julia
function (g::AbstractGPStruct)(val)
     return first(mean(g.gp_posterior(val)))
end
```
it worked for me.
Note that right now you are computing the gradient on the mean of the predictive distribution given a new output.

**Comment by willtebbutt** [comment]
You're right @theogf . My point about the objective function stands though -- the gradient w.r.t. the mean, or a single element of it, isn't the right thing to be computing.

**Comment by vikram-s-narayan** [comment]
@willtebbutt - The links you provided are super-helpful. I found the [YouTube video resource](https://www.youtube.com/watch?v=92-98SYOdlY) to be particularly helpful to me to build my intuition. Also, the suggested videos on videolectures.net does not open for me without Adobe Flash Player. However, that particular [video is also available on YouTube](https://www.youtube.com/watch?v=NegVuuHwa8Q).

Thanks for pointing out the need for logpdf to compute hyper-parameters. The reason why I'm computing the gradient on the mean is to keep the prediction function behaviour consistent with the rest of the surrogate models (in Surrogates.jl).

@theogf - Thanks for the suggested fix. That did the trick for me!
