### ISSUE TITLE
Stabilize `MeanFunction` API

### ISSUE THREAD

**Issue by simsurace** [JuliaGaussianProcesses/AbstractGPs.jl#356]
It would be nice to have an official API for mean functions. It could be minimalistic for now, but e.g. guarantee that `MeanFunction` is exported and maybe have a public method `meanvector` similar to `kernelmatrix`, that serves as a user-facing version of `_map_meanfunction`. @theogf 

Right now implementing non-standard mean functions requires relying on internals.

**Comment by theogf** [comment]
Solved in #357
