### ISSUE TITLE
CategoricalLikelihood compatibility with LatentGP

### ISSUE THREAD

**Issue by ancorso** [JuliaGaussianProcesses/AbstractGPs.jl#404]
I would like to model a multi-class dataset using `LatentGP`s and the `CategoricalLikelihood` (from GPLikelihoods.jl). The `CategoricalLikelihood` requires multiple latent GPs, and expects their output to be a `AbstractVector{<:AbstractVector{<:Real}}`. Instead, the design choice for multi-output GPs is to concatenate the outputs into one long vector, which is not what is necessary for a LatentGP with a `CategoricalLikelihood`. Below is an example:

```
gpm = GP(IndependentMOKernel(Matern52Kernel()))
x = rand(100)
X = MOInput(x, 3)

rand(gpm(X)) # produces a 300 element vector 

cgp = LatentGP(gpm, CategoricalLikelihood(), 1e-3)
cgpx = cgp(X)

res = rand(cgpx) # produces 300 values for `f` and a single sample for `y` because the softmax is applied over the full vector
```

Let me know if this is the wrong way of handling categorical likelihoods or if there is a recommendation on how to get this working out of the box. Happy to work on a PR.

**Comment by theogf** [comment]
Hey! Yes the interface is far from ideal right now, you can find a multi class example (using a different inference approach) here: https://juliagaussianprocesses.github.io/AugmentedGPLikelihoods.jl/dev/examples/categorical/

**Comment by ancorso** [comment]
It seems like perhaps this line: https://github.com/JuliaGaussianProcesses/AugmentedGPLikelihoods.jl/blob/41336971ee8882a147e996cf4e791831422da393/examples/categorical/script.jl#L138
should get reshaped into a `AbstractVector{<:AbstractVector{<:Normal}}`?

**Comment by theogf** [comment]
That's a good point! I will try to fix the script in the repo directly!

**Comment by ancorso** [comment]
> That's a good point! I will try to fix the script in the repo directly!

That would be a big help, thank you!
