### ISSUE TITLE
Avoid re-computing distance for stationary models

### ISSUE THREAD

**Issue by luiarthur** [JuliaGaussianProcesses/AbstractGPs.jl#43]
Hi,

First, thanks for this great package! Some of the features here are really slick.

My questions is whether it is possible to avoid re-computing distance matrices in the following example.

Basically, I'm interested in getting posterior predictives of the function `f` at new locations `xgrid`. Say I have posterior samples of the inverse range parameter (`rho`) of a squared exponential covariance function and I want to predict at new locations using each of those samples of `rho`. It seems the only option using the semantics below involves re-computing a distance matrix (which in theory needs to be computed only once). Is it possible to avoid re-computing the distance matrix?

```julia
using AbstractGPs, KernelFunctions, PyPlot, Distributions
import Random

# Make some data
Random.seed!(4)
num_obs = 10
x = randn(num_obs)
f(x) =  sin(3 * x) * sin(x) * (-1)^(x > 0)
y = f.(x);

# Make a grid of prediction locations.
num_new_locations = 100
xgrid = range(-3, 3, length=num_new_locations)

# Random inverse range parameters.
n_posterior_samples = 50
rhos = rand(Uniform(1, 2), n_posterior_samples)

# Predict at new locations (xgrid).
@time fs = [let
    kernel = transform(SqExponentialKernel(), rho)
    kernel += 1e-8 * WhiteKernel()  # needed to ensure covariance diagonal is positive.
    f = GP(kernel)
   
    # FIXME? This line involve re-computing a distance matrix from (a static) x.
    pfx = posterior(f(x, 1e-8), y)
    
    rand(pfx(xgrid))
end for rho in rhos];

# Plot results.
plt.scatter(x, y, c="black", zorder=3, s=50)
plt.xlabel("x")
plt.ylabel("y")
for f in fs
    plt.plot(xgrid, f, alpha=0.2, c="red")
end
```
![image](https://user-images.githubusercontent.com/5297817/89856452-29984b00-db4e-11ea-8ac8-3db4f42d3f47.png)

[1]: https://github.com/luiarthur/TuringBnpBenchmarks/blob/master/src/gp-binary/examples/agp.ipynb

**Comment by sharanry** [comment]
Hey! Thanks for opening the issue! I think with the current structure there no easy out-of-the-box way to improve this. 

One possible solution could be to use [`Memoize.jl`](https://github.com/JuliaCollections/Memoize.jl). We could use `@memoize` macro [here](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/0df9e8352d7d9f034f75de4d3639c0bb3b96c714/src/generic.jl#L9).

@willtebbutt any thoughts on this?

**Comment by willtebbutt** [comment]
Yeah. Unfortunately this is something that we're not easily able to support with our current semantics. We've had discussions about this kind of thing before, and the conclusion has always been that there aren't many situations / tasks in for which this is likely to be the computational bottleneck.

So I wonder whether this is really a bottleneck in your application, or whether the other computations involved in posterior simulation that can't be shared between samples are account for the vast majority of your compute time?

**Comment by luiarthur** [comment]
Thanks for the comments!

> So I wonder whether this is really a bottleneck in your application, or whether the other computations involved in posterior simulation that can't be shared between samples are account for the vast majority of your compute time?

Fair point. Admittedly, this isn't the bottleneck in my applications. I'm mostly asking as I'm benchmarking different GP packages and want to be fair with timings and provide explanations for differences in timings when possible.

I just want to confirm one more related thing. If I understand correctly, in the [NUTS example in the docs][1], the distance matrix is also re-computed every leapfrog step, correct?

[1]: https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev/examples/HMC/

**Comment by willtebbutt** [comment]
> I just want to confirm one more related thing. If I understand correctly, in the NUTS example in the docs, the distance matrix is also re-computed every leapfrog step, correct?

Yup, again for the same reason -- generally speaking changing the hypers necessitates recomputing everything.

**Comment by luiarthur** [comment]
Cool. That answers all my questions. Thanks!
