### ISSUE TITLE
[Question] is `sampleplot()` doing what it is supposed to?

### ISSUE THREAD

**Issue by 4aHxKzD** [JuliaGaussianProcesses/AbstractGPs.jl#57]
Is this the intended behavior of 

``` Julia
k = SqExponentialKernel()
f = GP(k)
sampleplot(f(rand(10)), 2; markersize=5)
```
?

![sampleplot](https://user-images.githubusercontent.com/57544666/92770944-5d0b0700-f392-11ea-8702-e72200871bba.png)

**Comment by willtebbutt** [comment]
Probably? These look like reasonable samples from the prior to me. Is this different from what you were expecting?

**Comment by 4aHxKzD** [comment]
Never mind, I got confused :P

**Comment by 4aHxKzD** [comment]
For some reason I was also expecting the mean and variance in addition to the samples.

**Comment by willtebbutt** [comment]
Oh I see. I think if you just `plot` a GP it should do that, should it not?

**Comment by 4aHxKzD** [comment]
it does indeed

**Comment by 4aHxKzD** [comment]
any ideas of simple tasks if I want to contribute to this package?
