### ISSUE TITLE
Small error in the ESS example: Incorrect use of train/test data in the last block

### ISSUE THREAD

**Issue by nathanaelbosch** [JuliaGaussianProcesses/AbstractGPs.jl#63]
This is really just a small error, but it might could actually be confusing to readers.

In the last block of code and plot in the [example on Approximate Inference with ESS](https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev/examples/EllipticalSliceSampling/), there are two mistakes:
1. both scatterplots are called on `x_train` and `y_train`, so that the final plot does not actually show the test data, and
2. the posterior is actually computed with the whole dataset (`x`, `y`), which I assume should be (`x_train`, `y_train`).

I will open a very small pull request with the corrections to resolve this issue, so I guess this should be resolved very quickly.

**Comment by willtebbutt** [comment]
Thanks for catching this!
