### ISSUE TITLE
AdvancedHMC example broken

### ISSUE THREAD

**Issue by devmotion** [JuliaGaussianProcesses/AbstractGPs.jl#91]
For some time the AdvancedHMC example has been broken, see e.g. https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/runs/1639170780?check_suite_focus=true#step:5:56:
```julia
┌ Warning: failed to run `@example` block in src/examples/HMC.md:149-161
│ ```@example HMC
│ samples, stats = sample(
│     hamiltonian,
│     proposal,
│     initial_params,
│     n_samples,
│     adaptor,
│     n_adapts;
│     progress=false
│ )
│ samples_mat = reduce(hcat, samples)';
│ nothing #hide
│ ```
│   c.value = PosDefException: matrix is not positive definite; Cholesky factorization failed.
└ @ Documenter.Expanders ~/.julia/packages/Documenter/6vUwN/src/Expanders.jl:563
```

**Comment by devmotion** [comment]
It's unstable since the implementation of `logp` is incorrect.

**Comment by willtebbutt** [comment]
> It's unstable since the implementation of logp is incorrect.

Is this something in this particular example, or an issue with `AbstractGPs` itself?

**Comment by devmotion** [comment]
No, just the example. I'll open a PR, I spotted some inconsistencies as well.
